sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "FdnGNFWi5s90Dt3TSKWEE7tB9oT5ypKNDgj1ItVrzskzkitiUfKFOsKoOkkCYFZ1x5MrVDY4+aXM2MBW+OqXqdrb/zm+f0Cda+OY1FbdTsrwT/WGL+Q3aqXglQaEES9QqwfhLeuhL3qQAl4kdG0E0W9xI1LI7b3HqTqL6OrgEe8sBjir7UrIwTBOSZvAXCwR6mOzoZQhwh5VmRIlpQMuXlm9fpcJLbv6UgB6nF0G5ii4sqrTrSuy4tzqzqSIjxkcKlvg9VJtTCduEo36fqis6OAeb81pJYwbVFP5nkXt2LbAuZNe1mINIubq0mvVJxFUaJilfjgcz4g1JOykw5DJuTh39/C3dnzryc113YBFywjyrBFD+p1pos01OmP8z1ESi9t71MjPfa8JLzNIZAjBPS0zpOaX7s8XcDJuzGfjo6kNjypkzGzMjzDYkSvQpbBNCP/6PiQPKrfAPOFcW0+m+XcHyNvtzCKJgk7DRLlKWqMAk5URd5up8mgOfMCPYamgob7/6HKyQ+VcnDjMzxshzP9DBJwbD9uMBM1wh3rKfzh7ZMrda90Ts7G6TqI4CAU5rueLi2RB3Bj6THUUBnM6cZkonHmKoulq3mxEdT3Mq2apsEuJvT3cDeeew6BmKnb6PIFXlk5T2Y0WKO7gZq+nvwERqJPajfE9PZjAY6Mb4Do="
  - secure: "s7zztkhJS2MTrngVNAdeso91Bbe2mKfQH2YHzhIu9DJBvP5b4grC4sXP1OXJyC+MFIBnbsCurcDwwEJDPZLFR0c9TKZXr3UWxVvi/cWmzCDpHShePzzl5xCkY/6TiC0Fit6z3uDKjX9hBkxlMlQgxkM82EVpx5M2yQEeA9O2z85zFQmU2NAZoeFV8RWKQPF4sdtrNqe0F5otpcVcGEcUgVBh2dlScNWdOXmXbTGayg0uf1Dbm/Dsb/hoiECvtSkwRpRWRX4GzXcXP6243oS2DRcqu4Y7pXpz9Z763HwnRbTyWli8HMSiyEojn2q+852CIXls5dUGtTdZeAKBEaCR32GemLg5w8N/x4l9DS6SBMVnR7wLXeyxg6wtNghK8YDibNuP47R01AcaMzIQKD3gZZhAFuQ34lMcCbyxA+onmwUJjq4riOfGLglxKs+y1N0iovzt17vPUYj1eQFdd3sCc1jn+QT3JpigWLUPYjBmkc83cZusuxg8G/AsSbDCoJQMVbA0PDhTOHRLLTcE1EQ7v32YSr+3ck32njyejrulFIaisGJF7khPeHrZcCix1uu+JcdUngfj/41vQvvgyQ+hGA/KA4UiaPiJnJTQU41Dobwi02hQP/leFaohAYCLUy/C7pF9+1xBh83MoxforTwK3ObRqkaqbOgXoxf8mXfHlSo="
  - secure: "teBWRNxJYAGIAEeUyOP5UuV5+FrnW3OUGMpd9R3rS+CIvLwe5Faea+SmbcOjYpinwnk5l4dU9CBjEFzkX7pB02JsrremLWuIvqgNSoB8ja1S4Aw6Hw+gzafvsV08L7oFEqFodLYNQGQzmVpuMMwbRp/6wniqCatfiD2VGhaXjwY6m0hKK3E2MuJpYNeUE+bYPeYJJERIZ1LWJ3k0W8xDQjacu01hWRlfHld4mz9siA2PUGGi0asZ2neic0uqkIvEZyG65SiaXOHNn2zm9cfyapEDKwboRQ7pnpi7C7v9Rw2OnVo65CRf/3bgwMK1I3KcOLaptIPmQKtweEKmZGaPPp4oVYDgwYs6SjgA1+4Va1fpHwKIFYmo3a4XSlXYjY+08YdF1HYVczYEC3/hGbaMyGia6lEBMW9Xjw/rCLQH85PJkI2CskyWhLDXeG00OanwPPUloNwoppxnR1+d5Y6xbs1FK7zD5/y8czGbp8O0CXSWqQUq7+rmIMEdwR/Op3FoCpsQ/u3mHW5BBVW5NJWLjrwx2OOX2uO5EDkv84uyQCy1WlrFxgcNoqYFGLHpbTdGazPnS8v0FHVvgpq11zZH9JvVnVXo2N/+9Fx/9FN+be1VP4YvM54K8TSRq3kasl634XBlOZtZxZ5fM+t/IEewnvkuuQJkttXvJXz0zGbd5nc="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
