sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "FdnGNFWi5s90Dt3TSKWEE7tB9oT5ypKNDgj1ItVrzskzkitiUfKFOsKoOkkCYFZ1x5MrVDY4+aXM2MBW+OqXqdrb/zm+f0Cda+OY1FbdTsrwT/WGL+Q3aqXglQaEES9QqwfhLeuhL3qQAl4kdG0E0W9xI1LI7b3HqTqL6OrgEe8sBjir7UrIwTBOSZvAXCwR6mOzoZQhwh5VmRIlpQMuXlm9fpcJLbv6UgB6nF0G5ii4sqrTrSuy4tzqzqSIjxkcKlvg9VJtTCduEo36fqis6OAeb81pJYwbVFP5nkXt2LbAuZNe1mINIubq0mvVJxFUaJilfjgcz4g1JOykw5DJuTh39/C3dnzryc113YBFywjyrBFD+p1pos01OmP8z1ESi9t71MjPfa8JLzNIZAjBPS0zpOaX7s8XcDJuzGfjo6kNjypkzGzMjzDYkSvQpbBNCP/6PiQPKrfAPOFcW0+m+XcHyNvtzCKJgk7DRLlKWqMAk5URd5up8mgOfMCPYamgob7/6HKyQ+VcnDjMzxshzP9DBJwbD9uMBM1wh3rKfzh7ZMrda90Ts7G6TqI4CAU5rueLi2RB3Bj6THUUBnM6cZkonHmKoulq3mxEdT3Mq2apsEuJvT3cDeeew6BmKnb6PIFXlk5T2Y0WKO7gZq+nvwERqJPajfE9PZjAY6Mb4Do="
  - secure: "s7zztkhJS2MTrngVNAdeso91Bbe2mKfQH2YHzhIu9DJBvP5b4grC4sXP1OXJyC+MFIBnbsCurcDwwEJDPZLFR0c9TKZXr3UWxVvi/cWmzCDpHShePzzl5xCkY/6TiC0Fit6z3uDKjX9hBkxlMlQgxkM82EVpx5M2yQEeA9O2z85zFQmU2NAZoeFV8RWKQPF4sdtrNqe0F5otpcVcGEcUgVBh2dlScNWdOXmXbTGayg0uf1Dbm/Dsb/hoiECvtSkwRpRWRX4GzXcXP6243oS2DRcqu4Y7pXpz9Z763HwnRbTyWli8HMSiyEojn2q+852CIXls5dUGtTdZeAKBEaCR32GemLg5w8N/x4l9DS6SBMVnR7wLXeyxg6wtNghK8YDibNuP47R01AcaMzIQKD3gZZhAFuQ34lMcCbyxA+onmwUJjq4riOfGLglxKs+y1N0iovzt17vPUYj1eQFdd3sCc1jn+QT3JpigWLUPYjBmkc83cZusuxg8G/AsSbDCoJQMVbA0PDhTOHRLLTcE1EQ7v32YSr+3ck32njyejrulFIaisGJF7khPeHrZcCix1uu+JcdUngfj/41vQvvgyQ+hGA/KA4UiaPiJnJTQU41Dobwi02hQP/leFaohAYCLUy/C7pF9+1xBh83MoxforTwK3ObRqkaqbOgXoxf8mXfHlSo="
  - secure: "UUebmLk/YZ04xfijv4snbrl5CPWmCVVykq27wAYntBdzSjet5Z3DeD/OaS04kdhtViMu03g/edtrJ0ic9ZtSfRWI9CEDvUugDXwkx4SqHmkzdXAm/ghzX8qEJskPEFjif2+qePPvF/BUnbxFTWeTSJ6cMphGGHfMeHbbHBYXWqZcrf6XZfDdbwg7dMz1nI/h7brl+siqfU/IIZHJAR4/nl5szT2toH1uSPNENmVy4GBHl2FIm28GCYcRxPAHUSiQZS5290utUqTlL6PLDUWbqhTHDzpmmfyYNPhdNW1z6Oz7NiyeGNGBiRiETuNlOSKvhdQlbvso182Crmr1A9wDv2SePCDTI9DJO07L8/cRhJGlRp3JkvGUDMEfLPtsOh8GfKevGrl5SvBizdo1al1Q8DqYq19kNOYvQtI+qV+BeiGTQGlNk1SD/T3zp73KHguUx4o/FVcelE/NyGB1TYhWMP9CzHBq0j6sxhVKutsLVn8MAbEbFHHdtwS9HT8aGHFdG5V4BzW45PjBGIZOxGauBfLGsLHYTXeWLhX/gJRA/s/DVyeWkTF9MlnydaIr89SaITuH4ZkzQVBaiWwggT5OrhpQ3tqlkHgWus95QxFplntA3Vv2jL9DPTf+n954QY80ZfGkH92X2K3+eVC889iI8V598x58rnZiYBaQBcMd8d0="
  - secure: "al4vMZQSlGBQqpBXhlGp9LVzihb3gqzCQhof9cSAchLrjI4sByhoaf7I1GMs3at2ntay6l7zhjEWSmCOm5GHWqwl7IwEKEBtTQLnXmtYzpxmcBEM2DH4+OBVLDcEUc9WlLRjbGN18L3nhr3wwm3y273EHzb9hWfdNl287oA9BmpuDxz9Yu9G3PtV773sN+lRxvptiLXfTsvkcY8wq6/vCoY+99wmu+/S+kNwrRp8KBpgmPncNB3sYAj7Q+OOQeW1Axto8Rwe65r1p2Zy9zfY6AEuyvNvtjojowXt1AHGbXQqcCH5fgYodrRVfUpI7PoWWIwbeR+jJgQJQrPrsZBYRvGvygJ/wNY3dUY3Empo7A3kodNCsSrsmtAPhwwao5/YbbvWpJuwxzzpU75lpZkWP+RTvHr5rqeHO09aVoTX1OfXwNpQfInWh4sXxuC/sP+u6fJ/guYBQHedVio1LMOxUX2nsj4ZgFyM6FyFIfuDU8EGMaQ0zN/QhppYrAbZNdfSJYO3eOIzgKinpScWP9omPpUUG7Z06VfrZD69KK23BBUghVIhwmUHojCIYLUUlfIShFEmSIhdzewjXr6qi0PyWvZcbuAoGAgH+myxHbBM3rFYFyUDA8NFR+sBOezdlkvVaxmL6R7FbLS4PlOmpjYIv+KF8ohtbBHqHjJFlaYKPIA="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
